################ Тесты для администратора #################

### Создать новую компетенцию (для администратора)
POST /api/competence/create HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1AbWFpbC5ydSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxMjIzODAzOH0.Ffkz-00uvRgJgrkVVsTc7Y6qeTVLMnWTMekmdttHlbo
Content-type: application/json; charset=utf-8

{
    "id": "EES",
    "name": "Экологические изыскания",
    "abbr": "ИЭИ"
}


### Редактировать компетенцию (для администратора)
PUT /api/competence/update/EES HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1AbWFpbC5ydSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxMjIzODAzOH0.Ffkz-00uvRgJgrkVVsTc7Y6qeTVLMnWTMekmdttHlbo
Content-type: application/json; charset=utf-8

{
    "id": "EES",
    "name": "Экологические изыскания",
    "abbr": "ИЭИ"
}

### Переупорядочить компетенцию вверх
PUT /api/competence/move_up/1 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80
Content-type: application/json; charset=utf-8

### Переупорядочить компетенцию вниз
PUT /api/competence/move_down/1 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80
Content-type: application/json; charset=utf-8

### Удалить компетенцию по id (для администратора)
DELETE /api/competence/delete/EES HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1AbWFpbC5ydSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTcxMjIzODAzOH0.Ffkz-00uvRgJgrkVVsTc7Y6qeTVLMnWTMekmdttHlbo


################ Тесты для всех #################


### Получить все компетенции
GET /api/competence/get_all HTTP/1.1
Host: localhost:7000

### Получить одну компетенцию по id
GET /api/competence/get_one/1 HTTP/1.1
Host: localhost:7000


################ Тесты для пользователя #################



### Получить все компетенции пользователя (для пользователя)
GET /api/competence/user/get_all HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQzNzc5M30.c1UKaNA4CcaFEcHArRAoGxPK2dYOuFEvxRSr7JduhKw

### Создать новую компетенцию пользователя (для пользователя)
POST /api/competence/user/create HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQzNzc5M30.c1UKaNA4CcaFEcHArRAoGxPK2dYOuFEvxRSr7JduhKw
Cookie: basketId=s%3A16.iSac0fWrebrE64iRKDOcvPdxLmnCyz96JGiKBb3xWKg
Content-type: application/json; charset=utf-8

{
    "id": "EES",
    "name": "Экологические изыскания",
    "shortName": "ИЭЭИ"
}


### Удалить компетенцию пользователя по id (для пользователя)
DELETE /api/competence/user/delete/38 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQzNzc5M30.c1UKaNA4CcaFEcHArRAoGxPK2dYOuFEvxRSr7JduhKw