################ Тесты для админа #################

### Получить все проекты (для администратора)
GET /api/project/admin/get_all HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80

### Получить все проекты одного пользователя (для администратора)
GET /api/project/admin/get_all/user/1 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80

### Получить один проект по id (для администратора)
GET /api/project/admin/get_one/6 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80

### Создать новый проект (для администратора)
POST /api/project/admin/create HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80
Content-type: application/json; charset=utf-8

{
    "name": "проект",
    "comment": "Вариант 1",
    "address": "адрес",
    "lendArea": 1234,
    "lendExtension": 12,
    "objectType": "линейный",
    "customer": "ООО Заказчик",
    "userId": 2,
    "lendArea": 100,
    "status": "в работе",
    "variants": [
        {
            "order": 1,
            "survey": "Химическое исследование грунта",
            "variant": "По гост",
            "unit": "объединённая проба",
            "price": 0,
            "quantity": 2,
            "subcategory": "Исследования грунтов",
            "category": "Лабораторные исследования",
            "objectType": "линейный",
            "normDoc": "п. 120 СанПиН 2.1.3684-21",
            "justification": "СП 502.1325800.2021 и др. нормативными документами не определён чёткий алгоритм расчёта количества пробных площадок для нелинейных объектов. При расчёте количества пробных площадок для настоящего объекта применяются следующие условия:",
            "variantProps": [
                {
                    "order": 1,
                    "description": "Количество точек проб, из которых отбитается объединённая (смешанная) проба",
                    "unit": "точечная проба",
                    "price": 200,
                    "quantity": "5"
                },
                {
                    "order": 2,
                    "description": "рh солевой вытяжки; свинец (валовая форма); кадмий (валовая форма); цинк (валовая форма); медь (валовая форма); мышьяк (валовая форма); ртуть (валовая форма); бенз(а)пирен (валовая форма); никель (валовая форма); нефтепродукты; гумус; общий азот",
                    "unit": "список определяемых показателей",
                    "price": 10000,
                    "quantity": 1
                }
            ]
        }
    ]
}

### Удалить проект по id (для администратора)
DELETE /api/project/admin/delete/37 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80


################ Тесты для простого пользователя #################

### Получить все проекты пользователя (для пользователя)
GET /api/project/user/get_all HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQzNzc5M30.c1UKaNA4CcaFEcHArRAoGxPK2dYOuFEvxRSr7JduhKw

### Получить один проект поьзователя по id (для пользователя)
GET /api/project/user/get_one/38 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQzNzc5M30.c1UKaNA4CcaFEcHArRAoGxPK2dYOuFEvxRSr7JduhKw


### Создать новый проект (для пользователя)
POST /api/project/user/create HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQzNzc5M30.c1UKaNA4CcaFEcHArRAoGxPK2dYOuFEvxRSr7JduhKw
Cookie: basketId=s%3A16.iSac0fWrebrE64iRKDOcvPdxLmnCyz96JGiKBb3xWKg
Content-type: application/json; charset=utf-8

{
    "name": "проект",
    "comment": "Вариант 2",
    "address": "адрес",
    "lendArea": 1234,
    "lendExtension": 12,
    "objectType": "линейный",
    "customer": "ООО Заказчик",
    "userId": 2,
    "lendArea": 100,
    "status": "в работе"
}


### Удалить проект по id (для пользователя)
DELETE /api/project/user/delete/38 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQzNzc5M30.c1UKaNA4CcaFEcHArRAoGxPK2dYOuFEvxRSr7JduhKw