### Получить все подкатегории исследований
GET /api/subcategory/get_all HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQ0MDk0Mn0.OZMYwt55fqH7SUPpTkOI3p44Aeqd-k0TBK_D6WYgr9g

### Получить одину подкатегорию исследований
GET /api/subcategory/get_one/1 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJ1c2VyQG1haWwucnUiLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcwMTQ0MDk0Mn0.OZMYwt55fqH7SUPpTkOI3p44Aeqd-k0TBK_D6WYgr9g

### Создать новую подкатегорию исследований
POST /api/subcategory/create HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDQxMTI4fQ.Lr2bDW6Yhm7DbDTX0V8KP1CyHmuIn4X9WZOEsWDGRzE
Content-type: application/json; charset=utf-8

{
    "order": 2,
    "name": "Радиационные исследования",
    "categoryId": "2"
}

### Обновить подкатегорию исследований
PUT /api/subcategory/update/1 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDQxMTI4fQ.Lr2bDW6Yhm7DbDTX0V8KP1CyHmuIn4X9WZOEsWDGRzE
Content-type: application/json; charset=utf-8

{
    "order": 1,
    "name": "Спрвки ЦГМС",
    "categoryId": "1"
}

### Переупорядочить субкатегорию вверх
PUT /api/subcategory/move_up/1 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80
Content-type: application/json; charset=utf-8

{
    "categoryId": "1"
}

### Переупорядочить субкатегорию вниз
PUT /api/subcategory/move_down/1 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDM1MDc2fQ.gai7W4SvWDJ8_q2KgfBa5z_Py_w9fzb7xga0Ql_yH80
Content-type: application/json; charset=utf-8

{
    "categoryId": "1"
}

### Удалить подкатегорию исследований
DELETE /api/subcategory/delete/3 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDQxMTI4fQ.Lr2bDW6Yhm7DbDTX0V8KP1CyHmuIn4X9WZOEsWDGRzE