### Получить все варианты исследований
GET /api/variant/get_all HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhb...XVCJ9.eyJpZ...2NDR9.eDlzf...87TTA

### Получить один вариант исследований
GET /api/variant/get_one/3 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhb...XVCJ9.eyJpZ...2NDR9.eDlzf...87TTA

### Создать новый вариант исследований
POST /api/variant/create HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDQxMTI4fQ.Lr2bDW6Yhm7DbDTX0V8KP1CyHmuIn4X9WZOEsWDGRzE
Content-type: application/json; charset=utf-8

{
    "order": 2,
    "description": "По линейн",
    "price": null,
    "normDocId": 1,
    "justificationId": 1,
    "categoryId": 1,
    "subcategoryId": 1,
    "unitId": 1,
    "surveyId": 1,
    "objectTypeId": 2,
    "handlerId": null,
    "props": [
        {
            "order": 1,
            "description": "Количество точек проб, из которых отбитается объединённая (смешанная) проба",
            "unit": "точечная проба",
            "price": 200,
            "quantity": "5"
        },
        {
            "order": 2,
            "description": "рh солевой вытяжки; свинец (валовая форма); кадмий (валовая форма); цинк (валовая форма); медь (валовая форма); мышьяк (валовая форма); ртуть (валовая форма); бенз(а)пирен (валовая форма); никель (валовая форма); нефтепродукты; гумус; общий азот",
            "unit": "список определяемых показателей",
            "price": 10000,
            "quantity": 1
        }
    ]
}



### Обновить вариант исследований
PUT /api/variant/update/4 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDQxMTI4fQ.Lr2bDW6Yhm7DbDTX0V8KP1CyHmuIn4X9WZOEsWDGRzE
Content-type: application/json; charset=utf-8

{
    "order": 2,
    "description": "Ручной расчёт",
    "price": null,
    "normDocId": 1,
    "justificationId": 1,
    "categoryId": 1,
    "subcategoryId": 1,
    "unitId": 1,
    "surveyId": 1,
    "objectTypeId": 1,
    "handlerId": null,
    "props": [
        {
            "order": 1,
            "description": "Количество точек проб, из которых отбитается объединённая (смешанная) проба",
            "unit": "точечная проба",
            "price": 200,
            "quantity": "5"
        },
        {
            "order": 2,
            "description": "рh солевой вытяжки; свинец (валовая форма); кадмий (валовая форма); цинк (валовая форма); медь (валовая форма); мышьяк (валовая форма); ртуть (валовая форма); бенз(а)пирен (валовая форма); никель (валовая форма); нефтепродукты; гумус; общий азот",
            "unit": "список определяемых показателей",
            "price": 10000,
            "quantity": 1
        }
    ]
}

### Удалить вариант исследований
DELETE /api/variant/delete/4 HTTP/1.1
Host: localhost:7000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzAxNDQxMTI4fQ.Lr2bDW6Yhm7DbDTX0V8KP1CyHmuIn4X9WZOEsWDGRzE